// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title KYCProofVerifier
 * @notice Groth16 zk-SNARK verifier for KYC identity proofs
 * @dev Verifies that a prover knows a valid identity secret satisfying KYC constraints
 *      WITHOUT revealing the identity itself. Circuit: circom/kyc_proof.circom
 *
 * Public Inputs layout (pubInputs[]):
 *   [0] identityCommitment   - Poseidon(nullifier, secret)
 *   [1] documentCommitment   - Poseidon(docHash, salt)
 *   [2] ageAbove18           - 1 if age >= 18, 0 otherwise
 *   [3] notSanctioned        - 1 if not on sanctions list
 *   [4] jurisdictionMerkleRoot - Root of jurisdiction allowlist Merkle tree
 *   [5] timestamp            - block.timestamp at proof generation
 */
contract KYCProofVerifier {

    // Groth16 BN254 verification key — generated by snarkjs after trusted setup
    // In production: replace with actual ceremony outputs (Powers of Tau)
    struct VerifyingKey {
        uint256[2]    alpha;
        uint256[2][2] beta;
        uint256[2][2] gamma;
        uint256[2][2] delta;
        uint256[2][]  ic;  // One per public input + 1
    }

    VerifyingKey internal vk;
    bool         public  keyInitialised;
    address      public  immutable admin;

    event VerifyingKeySet(uint256 timestamp);

    error KeyNotInitialised();
    error InvalidProofFormat();
    error Unauthorised();

    constructor(address _admin) {
        admin = _admin;
    }

    /**
     * @notice Load the Groth16 verifying key (done once after trusted setup ceremony)
     * @dev In production, this is called once during deployment with ceremony outputs
     */
    function setVerifyingKey(
        uint256[2]    calldata alpha,
        uint256[2][2] calldata beta,
        uint256[2][2] calldata gamma,
        uint256[2][2] calldata delta,
        uint256[2][]  calldata ic
    ) external {
        require(msg.sender == admin, "Unauthorised");
        require(!keyInitialised,     "Already set");
        require(ic.length == 7,      "Need 6 public inputs + 1 IC point");

        vk.alpha = alpha;
        vk.beta  = beta;
        vk.gamma = gamma;
        vk.delta = delta;

        for (uint i = 0; i < ic.length; i++) {
            vk.ic.push(ic[i]);
        }

        keyInitialised = true;
        emit VerifyingKeySet(block.timestamp);
    }

    /**
     * @notice Verify a Groth16 proof
     * @param a  Proof element A (G1 point)
     * @param b  Proof element B (G2 point)
     * @param c  Proof element C (G1 point)
     * @param pubInputs Public inputs array
     * @return bool True if proof is valid
     */
    function verifyProof(
        uint256[2]    calldata a,
        uint256[2][2] calldata b,
        uint256[2]    calldata c,
        uint256[]     calldata pubInputs
    ) external view returns (bool) {
        if (!keyInitialised) revert KeyNotInitialised();
        if (pubInputs.length != 6) revert InvalidProofFormat();

        return _groth16Verify(a, b, c, pubInputs);
    }

    /**
     * @dev BN254 pairing-based Groth16 verification
     *      Using EIP-197 precompile (address 0x08) for pairing check
     */
    function _groth16Verify(
        uint256[2]    calldata a,
        uint256[2][2] calldata b,
        uint256[2]    calldata c,
        uint256[]     calldata pubInputs
    ) internal view returns (bool) {
        // Compute linear combination: vk_x = IC[0] + sum(pubInputs[i] * IC[i+1])
        uint256[2] memory vk_x;
        vk_x[0] = vk.ic[0][0];
        vk_x[1] = vk.ic[0][1];

        for (uint256 i = 0; i < pubInputs.length; i++) {
            uint256[2] memory scaled = _ecMul(vk.ic[i + 1], pubInputs[i]);
            (vk_x[0], vk_x[1]) = _ecAdd(vk_x[0], vk_x[1], scaled[0], scaled[1]);
        }

        // Pairing check: e(A, B) = e(alpha, beta) * e(vk_x, gamma) * e(C, delta)
        return _pairingCheck(a, b, vk_x, vk.gamma, c, vk.delta);
    }

    // ─── BN254 Precompile Wrappers ────────────────────────────────────────────

    function _ecAdd(
        uint256 x1, uint256 y1, uint256 x2, uint256 y2
    ) internal view returns (uint256 rx, uint256 ry) {
        uint256[4] memory input = [x1, y1, x2, y2];
        uint256[2] memory result;
        bool success;
        assembly {
            success := staticcall(gas(), 0x06, input, 128, result, 64)
        }
        require(success, "ecAdd failed");
        return (result[0], result[1]);
    }

    function _ecMul(
        uint256[2] memory point, uint256 scalar
    ) internal view returns (uint256[2] memory result) {
        uint256[3] memory input = [point[0], point[1], scalar];
        bool success;
        assembly {
            success := staticcall(gas(), 0x07, input, 96, result, 64)
        }
        require(success, "ecMul failed");
    }

    function _pairingCheck(
        uint256[2] calldata a,
        uint256[2][2] calldata b,
        uint256[2] memory vk_x,
        uint256[2][2] memory gamma,
        uint256[2] calldata c,
        uint256[2][2] memory delta
    ) internal view returns (bool) {
        // Build 4-pairing check input (each pair: G1 point, G2 point)
        uint256[24] memory input;

        // Pair 1: (-A, B)
        input[0]  = a[0];
        input[1]  = BN254_FIELD_MODULUS - a[1]; // negate
        input[2]  = b[0][1]; input[3] = b[0][0];
        input[4]  = b[1][1]; input[5] = b[1][0];

        // Pair 2: (vk_x, gamma)
        input[6]  = vk_x[0];   input[7]  = vk_x[1];
        input[8]  = gamma[0][1]; input[9]  = gamma[0][0];
        input[10] = gamma[1][1]; input[11] = gamma[1][0];

        // Pair 3: (C, delta)
        input[12] = c[0];   input[13] = c[1];
        input[14] = delta[0][1]; input[15] = delta[0][0];
        input[16] = delta[1][1]; input[17] = delta[1][0];

        // Pair 4: (alpha, beta)  — combined with negated A pairing
        input[18] = vk.alpha[0]; input[19] = vk.alpha[1];
        input[20] = vk.beta[0][1]; input[21] = vk.beta[0][0];
        input[22] = vk.beta[1][1]; input[23] = vk.beta[1][0];

        uint256[1] memory out;
        bool success;
        assembly {
            success := staticcall(gas(), 0x08, input, 768, out, 32)
        }
        require(success, "Pairing check failed");
        return out[0] == 1;
    }

    uint256 constant BN254_FIELD_MODULUS =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;
}
